# Generated by Django 3.2.3 on 2021-05-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('notifyEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('parentForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formHandler.formmodel')),
            ],
        ),
    ]
