# Generated by Django 3.2.3 on 2021-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formHandler', '0002_formmodel_successredirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='notifyEmail',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='nofiryTelegram',
            field=models.ManyToManyField(blank=True, to='formHandler.TelegramNotify'),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='notifyEmails',
            field=models.ManyToManyField(blank=True, to='formHandler.EmailNotify'),
        ),
    ]
