# Generated by Django 3.2.3 on 2021-11-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formHandler', '0003_auto_20211125_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='nofiryTelegram',
            new_name='notifyTelegram',
        ),
    ]
